//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Job_Finder.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int favorite_id { get; set; }
        public Nullable<int> candidate_id { get; set; }
        public Nullable<int> job_id { get; set; }
    
        [JsonIgnore]
        public virtual CandidateProfile CandidateProfile { get; set; }
        [JsonIgnore]
        public virtual JobPosting JobPosting { get; set; }
    }
}
