//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Job_Finder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IT_JOB_FINDEREntities : DbContext
    {
        public IT_JOB_FINDEREntities()
            : base("name=IT_JOB_FINDEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CandidateProfile> CandidateProfiles { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<JobApplication> JobApplications { get; set; }
        public virtual DbSet<JobPosting> JobPostings { get; set; }
        public virtual DbSet<JobSkill> JobSkills { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<SkillRequirement> SkillRequirements { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
