//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Job_Finder.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string full_name { get; set; }
        public string role { get; set; }
        public string imageURL { get; set; }

        [JsonIgnore]
        public virtual CandidateProfile CandidateProfile { get; set; }
        [JsonIgnore]
        public virtual Employer Employer { get; set; }
    }
}
